version: 2
updates:
  # Обновление зависимостей npm (зависимости проекта)
  - package-ecosystem: 'npm'
    directory: '/' # Путь к каталогу, где находится файл package.json
    schedule:
      interval: 'weekly' # Интервал обновлений: ежедневно, еженедельно или ежемесячно
    open-pull-requests-limit: 10 # Максимальное количество открытых pull request'ов от Dependabot

  # Обновление зависимостей GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/' # Путь к каталогу, где находятся файлы конфигурации GitHub Actions
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
