import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home | Abdul Basit',
  description: 'Generated by abdul basit interesting blogs,projects,smile and others... 2023',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/public/logo.png?v=4'],
    shortcut: ['/public/logo.png'],
  },
  alternates: {
    canonical: 'http://www.a-bd.me/',
  },
}

import React from 'react'
import dynamic from 'next/dynamic'

const HomeMain = dynamic(() => import('@/app/(home)/components/home-main'))
const HomeLinks = dynamic(() => import('@/app/(home)/components/home-links'))
const HomeAboutMe = dynamic(() => import('@/app/(home)/components/home-aboutme'))
const HomeLatestPosts = dynamic(() => import('@/app/(home)/components/home-latest-posts'))

export default function Home() {
  return (
    <main className="container pb-28">
      <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W7FF9K85" height="0" width="0" style={{ display: 'none', visibility: 'hidden' }}></iframe>
      </noscript>
      <div className="pt-[9rem] max-md:pt-[8rem] flex flex-col gap-8">
        <HomeMain />
        <HomeLinks />
        <HomeAboutMe />
      </div>
      <HomeLatestPosts />
    </main>
  )
}
