import React from 'react'

import { Metadata } from 'next'
import { Locate } from 'lucide-react'

import Cards from '@/app/(home)/components/bento/card'
import HomeMain from '@/app/(home)/components/home-main'
import PinnedProjects from '@/app/(home)/pinned-projects'
import HomeLatestPosts from '@/app/(home)/components/home-latest-posts'

export const metadata: Metadata = {
  title: 'Home | Abdul Basit',
  description: 'Generated by abdul basit interesting blogs,projects,smile and others... 2023',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/public/logo.png?v=4'],
    shortcut: ['/public/logo.png'],
  },
  alternates: {
    canonical: 'http://www.a-bd.me/',
  },
}

export default function Home() {
  return (
    <main className="container pb-[180px]">
      <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W7FF9K85" height="0" width="0" style={{ display: 'none', visibility: 'hidden' }}></iframe>
      </noscript>
      <div className="pt-[5rem] max-md:pt-[4rem] flex flex-col gap-10">
        <div className={'flex flex-col gap-8'}>
          <div>
            <HomeMain />
          </div>
        </div>
        <Cards />
      </div>
      <div className="relative">
        <img src="https://i.ibb.co/25pf844/Screenshot-2024-09-21-162603.png" alt="map" className="w-full mt-2 h-[150px] rounded-lg object-cover bg-cover" />
        <div className="absolute bottom-2 left-2 flex flex-col rounded-lg bg-neutral-100/75 p-1.5 leading-none backdrop-blur dark:bg-neutral-900/75">
          <p className="m-0 text-sm font-medium flex items-center gap-1">
            Location <Locate size={12} />
          </p>
          <p className="m-0 text-xs font-semibold text-primary">Tashkent,Uzbekistan</p>
        </div>
      </div>
      <PinnedProjects />
      <HomeLatestPosts />
    </main>
  )
}
